### ISSUE TITLE
Get rid of blank page after each content page in PDF generated by recent versions of Chrome

### ISSUE THREAD

**Issue by doersino** [doersino/markdeep-thesis#3]
Recent versions of Chrome yield a blank page after every content page. I think this is a Bindery issue, but I haven't yet done enough testing to be sure of that.

**For now, any PDF editor (such as Preview on macOS) or `pdftk <FILE.pdf> cat even output <OUTPUT.pdf>` should allow you to remove those blank pages.**

(This behavior wasn't present last November when I used a pre-release version of this tool to write my own thesis – I went back and checked.)

**Comment by tibor0991** [comment]
Apparently, the issue has been fixed in Chrome 80.0.3987.122, can anyone confirm this?

BTW, thank you so much for this template, you made my thesis look sharp!

**Comment by doersino** [comment]
> Apparently, the issue has been fixed in Chrome 80.0.3987.122, can anyone confirm this?

You're right, it looks like the most recent version of Chrome functions as expected again. Brilliant!

> BTW, thank you so much for this template, you made my thesis look sharp!

You're most welcome. 👍
